ALTER TABLE product
ADD COLUMN description TEXT,

ADD COLUMN purchase_price NUMERIC(12,2) NOT NULL DEFAULT 0,

ADD COLUMN selling_price NUMERIC(12,2) NOT NULL DEFAULT 0,

ADD COLUMN minimum_stock NUMERIC(12,3) NOT NULL DEFAULT 0;